const data = [
  {
    institute: "IIT Bhilai",
    branches: [
      "Computer Science and Engineering",
      "Chemistry",
      "Electrical Engineering",
      "Mathematics",
      "Mechanical Engineering",
      "Physics",
    ],
  },
  {
    institute: "IIT (BHU) Varanasi",
    branches: [
      "Biochemical Engineering",
      "Biomedical Engineering",
      "Ceremic Engineering and Technology",
      "Chemical Engineering",
      "Chemistry",
      "Civil Enginnering",
      "Computer Science and Engineering",
      "Electrical Engineering",
      "Electronics Engineering",
      "Humanistic Studies",
      "Materials Science and Technology",
      "Mathematics Science",
      "Mechanical Engineering",
      "Metallurigical Engineering",
      "Mining Enginnering",
      "Pharmaceutical Engineering and Technology",
      "Physics",
    ],
  },
  {
    institute: "IIT Bhubaneswar",
    branches: [
      "Biosciences",
      "Chemistry",
      "Civil Enginnering (School of Infrastructure)",
      "Computer Science and Engineering",
      "Electrical Engineering",
      "Electronics & Communication Engineering",
      "Mathematics",
      "Mechanical Engineering",
      "Metallurigical & Materials Engineering",
      "Physics",
      "School of Earth, Ocean and Climate Sciences",
      "School of Humanities, Social Sciences & Management",
    ],
  },
  {
    institute: "IIT Bombay",
    branches: [
      "Aerospace Engineering",
      "Biosciences and Bioengineering",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer Science & Engineering",
      "Earth Sciences",
      "Electrical Engineering",
      "Energy Science and Engineering",
      "Environmental Science and Engineering",
      "Humanities & Social Sciences",
      "IDC School of Design (IDC SoD)",
      "Mathematics",
      "Mechanical Engineering",
      "Metallurgical Engineering & Materials Science",
      "Physics",
      "Shailesh J. Mehta School of Management (SJMSoM)",
    ],
  },
  {
    institute: "IIT Delhi",
    branches: [
      "Applied Mechanics",
      "Biochemical Engineering and Biotechnology",
      "Chemical Engineering",
      "Chemistry",
      "Civil Engineering",
      "Computer Science and Engineering",
      "Design",
      "Electrical Engineering",
      "Energy Science and Engineering",
      "Humanities and Social Sciences",
      "Management Studies",
      "Materials Science and Engineering",
      "Mathematics",
      "Mechanical Engineering",
      "Physics",
      "Textile and Fibre Engineering",
    ],
  },
];

export default data;
